### ISSUE TITLE
Home - Survol collectif

### ISSUE THREAD

**Issue by 5AMsan** [5AMsan/PepiteWorld#1]

**Comment by 5AMsan** [comment]
Alors, là , je sus vraiment bloqué. Je ne trouve pas de solution à notre portée pour faire ce script. On peut chercher une alternative ?

**Comment by Pepite-Atelier** [comment]
Ouais pas de soucis :) ! J'ai crée un effet qui reprend le même principe que pour les images du studio mais avec de la typo !
Qu'en penses-tu ? Je n'arrive pas, par contre, à faire passer les noms sur l'onglet avec le logo Pepite... tu saurais comment faire ?

**Comment by Pepite-Atelier** [comment]
J'ai trouvé un effet qui ressemble à ce qu'on voulait faire au départ !!! 
C'est ca : https://codepen.io/anishmprasad/pen/XgKoRG

Je l'ai modifié en enlevant le pause sur les hovers, la typo et les couleurs. Je l'ai implanté dans le site ici : /www/wp-content/uploads/js-noms et je l'ai ajouté au hover du mot 2015 (pour conserver l'effet du collectif). 

Alors, est-ce qu'il est possible de contenir la zone du rebond à la zone du contenu de la page d'accueil (pour qu'ils ne passent pas sous les onglets) ? Est-il également possible d'enclencher le script que quand on est sur le mot 2015 ? Pour le moment je l'ai juste caché quand nous ne somme pas sur 2015 mais j'ai peur que ca fume le processeur ^^ 

Si c'est trop compliqué on garde l'effet que j'ai fait sur collectif ;)
