### ISSUE TITLE
Direction Artistique - Page globale

### ISSUE THREAD

**Issue by Pepite-Atelier** [5AMsan/PepiteWorld#10]
- [x] Lorsque on navigue entre des éditions et que l'on revient sur la page D.A nous rencontrons deux problèmes : 

- L'affichage d'un bandeau avec information etc.. : 

![Capture d’écran 2020-12-08 à 14 29 43](https://user-images.githubusercontent.com/75670610/101490231-5b85b680-3962-11eb-905b-7e0168a5a3d7.png)

- Le bloc des projets se retrouve parfois collé en haut : 

![Capture d’écran 2020-12-08 à 14 31 57](https://user-images.githubusercontent.com/75670610/101490336-7e17cf80-3962-11eb-9904-7417d2a90c6a.png)

- [x] Lorsque l'on charge pour la première fois la page, les miniatures sont contenus dans un conteneur qui ne prend pas l'ensemble de la page. Au second chargement ou lorsque l'on revient d'un projet, le conteneur des miniatures prend bien l'ensemble de la page

**Comment by bast** [comment]
Was a different user intended to be notified?

**Comment by Pepite-Atelier** [comment]
@bast, sorry it was a mistake ! Have a good day !
