### ISSUE TITLE
Direction Artistique - Projet

### ISSUE THREAD

**Issue by Pepite-Atelier** [5AMsan/PepiteWorld#11]
- [x] Le compteur d’images ne correspond pas au nombre d'images du projet
- [x] Le compteur d’images n'affiche pas le bon numéro de l'image en cours
- [x] Régler le slider pour que les images et les vidéos fassent la même largeur (image en 900x581), hauteur fixe du slider basé sur la hauteur de la fenêtre et le contenu centré en hauteur
- [x] Intégration des curseurs flèche pour le slider
- [x] Lorsque la popup des informations et ouverte puis fermée, le slider ne fonctionne plus
- [x] La navigation entre les projets ne fonctionne pas et affiche une page blanche
- [x] Les players vidéos se lancent puis bloquent

**Comment by 5AMsan** [comment]
les curseurs sont ceux reçus en SVG, ils sont intégrés. Si vous ne les voyez pas, on regardera d'ou ça vient.

**Comment by Pepite-Atelier** [comment]
- [ ]  La navigation entre les projets ne fonctionne pas chez nous, nous avons une page blanche :
- [ ] Concernant la taille des images, elles sont trop petites...il faudrait qu'elles fassent 900px de large. Quand je regarde via le code source, elles sont en 640px par défaut. 
![Capture d’écran 2021-01-05 à 17 23 34](https://user-images.githubusercontent.com/75670610/103674252-d6041f00-4f7e-11eb-984a-2a320a3c807b.png)
- [ ] Le payer video marche chez toi ? Nous avons toujours le même soucis de lecteur qui se bloque
- [ ] Les images passent sur la barre de menu quand on est sur grande résolution 2880x1800 : 
<img width="1680" alt="Capture d’écran 2021-01-05 à 11 18 33" src="https://user-images.githubusercontent.com/75670610/103675293-0ef0c380-4f80-11eb-843f-d1ca41cd0b7f.png">
<img width="1671" alt="Capture d’écran 2021-01-05 à 11 19 01" src="https://user-images.githubusercontent.com/75670610/103675312-144e0e00-4f80-11eb-90fa-c0932d6c3a76.png">

**Comment by 5AMsan** [comment]
- [x]  La navigation entre les projets ne fonctionne pas chez nous, nous avons une page blanche

**Comment by 5AMsan** [comment]
- [x] Concernant la taille des images, elles sont trop petites...il faudrait qu'elles fassent 900px de large. Quand je regarde via le code source, elles sont en 640px par défaut. 
![Capture d’écran 2021-01-05 à 17 23 34](https://user-images.githubusercontent.com/75670610/103674252-d6041f00-4f7e-11eb-984a-2a320a3c807b.png)

**Comment by 5AMsan** [comment]
- [x] Le payer video marche chez toi ? Nous avons toujours le même soucis de lecteur qui se bloque

**Comment by 5AMsan** [comment]
> * [x]   La navigation entre les projets ne fonctionne pas chez nous, nous avons une page blanche

Je n'arrive pas à reproduire. Bastien, passe en mode débug sur ton poste pour me donner des infos plz**

**Comment by 5AMsan** [comment]
> * [x]  Le payer video marche chez toi ? Nous avons toujours le même soucis de lecteur qui se bloque

Je n'arrive pas à reproduire. Bastien, passe en mode débug sur ton poste pour me donner des infos plz**

**Comment by 5AMsan** [comment]
> * [ ]  Les images passent sur la barre de menu quand on est sur grande résolution 2880x1800 :
> 
> <img alt="Capture d’écran 2021-01-05 à 11 18 33" width="1680" src="https://user-images.githubusercontent.com/75670610/103675293-0ef0c380-4f80-11eb-843f-d1ca41cd0b7f.png">
> 
> <img alt="Capture d’écran 2021-01-05 à 11 19 01" width="1671" src="https://user-images.githubusercontent.com/75670610/103675312-144e0e00-4f80-11eb-90fa-c0932d6c3a76.png">

Je n'arrive pas à reproduire. Bastien, passe en mode débug sur ton poste pour me donner des infos plz

**Comment by Pepite-Atelier** [comment]
- [ ] Problème de ratio, images et vidéo du slider qui passent sur le boutons infos et compteur quand petite résolution

**Comment by Pepite-Atelier** [comment]
- [ ] Ajout d'un bouton d'ouverture et de fermeture du panneau projets, je t'ai maj la maquette sur le drive. Il faudrait que le bouton fasse la même hauteur que les autres boutons et les cases du panneau (enfin ce qui est déja le cas actuellement sur le site)  Exemple ici : https://bureauborsche.com/projects

Merci 💯  !

**Comment by 5AMsan** [comment]
Peux-tu me sortir tes maquettes en PDF multipage ou en image / planche plz Bastien ?
