### ISSUE TITLE
Fonderie - Font

### ISSUE THREAD

**Issue by Pepite-Atelier** [5AMsan/PepiteWorld#14]
- [x] Le testeur typo des pages typographie n'est pas accessible (lorsque l'on clique dessus il ne se passe rien)

**Comment by Pepite-Atelier** [comment]
- Comment rentrons-nous les liens pour les boutons des fonts ?

- [ ] Pour le bouton download, serait-il possible d'ajouter au click une pop-up comme les mentions légales avec un petit paragraphe du style : " Nous concevons des polices libres / open source. Cela signifie que vous pouvez les utiliser, les modifier et les redistribuer librement en créditant l'auteur. Vous pouvez soutenir notre activité, et notre engagement en faisant un don. Ainsi, nous pourrons continuer à concevoir et à publier de nouvelles polices régulièrement." avec dessous deux boutons : download et support us ?

**Comment by 5AMsan** [comment]
Concernant l'option d'alignement dans FontSampler, c'est un bug de FontSampler que nous n'avions pas avant, je pense que le dev va passer une MAJ dans pas très longtemps. En tout cas, on ne peut pas y faire grand chose je crois.

**Comment by Pepite-Atelier** [comment]
J'ai forcé le testeur en mettant un text-align:center ;) 
Par contre on a un bug quand on est sur une font et qu'on revient avec la flèche de retour du navigateur sur la page de sélection de font (pas celle qui est prévu dans la page) :

![Capture d’écran 2021-01-14 à 10 21 11](https://user-images.githubusercontent.com/75670610/104570481-42071700-5652-11eb-98ee-d4cba6d7316f.png)

**Comment by 5AMsan** [comment]
![image](https://user-images.githubusercontent.com/3309793/105217655-7009c100-5b54-11eb-9b74-b19032867286.png)
J'ai pas reproduit avec un cache propre

**Comment by Pepite-Atelier** [comment]
Nous avons tester avec un cache clean et sur un navigateur privée, il y a toujours cette page de code au retour d'une font sur la fonderie avec le retour natif du navigateur. On peut se capter pour en parler si tu veux ? je n'ai pas bien compris ta capture ^^

**Comment by 5AMsan** [comment]
En effet, c'est bien un souci de cache mais pas du tout comme je l'avais cru.
Ça doit passer maintenant.
