### ISSUE TITLE
Edition - Page globale

### ISSUE THREAD

**Issue by Pepite-Atelier** [5AMsan/PepiteWorld#15]
- [x] Rajouter les infos en hover des éditions
![Capture d’écran 2020-12-08 à 15 14 16](https://user-images.githubusercontent.com/75670610/101494799-12d0fc00-3968-11eb-8f77-fb6e340f8b71.png)

**Comment by 5AMsan** [comment]
J'ai que le titre à ajouter

**Comment by Pepite-Atelier** [comment]
- Peux-tu créer une catégorie Fanzine afin qu'on puisse à l'avenir avoir différentes catégories (affiches, fanzines, etc.) ? 
- Peux-tu ajouter également un champ de prix dans le back office des éditions qui sera repris dans le hover comme sur la capture ? Sinon on peut l'intégrer direct au titre de la publication ca marche aussi 👍

**Comment by 5AMsan** [comment]
Fais un nouveau ticket pour les styles si nécessaire.

**Comment by Pepite-Atelier** [comment]
Pour le hover, on peut supprimer " • " avant la catégorie et le remplacer par un <br> que la catégorie et le prix passent sous le titre ? 

![Capture d’écran 2021-01-07 à 16 32 37](https://user-images.githubusercontent.com/75670610/103911240-1215bc00-5106-11eb-8829-6aa5162322f7.png)
