### ISSUE TITLE
Edition - Single

### ISSUE THREAD

**Issue by Pepite-Atelier** [5AMsan/PepiteWorld#16]
- [x] Le compteur d’images ne correspond pas au nombre d'images du projet
- [x]  Le compteur d’images n'affiche pas le bon numéro de l'image en cours
- [x]  Régler le slider pour que les images soient en 900x581, hauteur fixe du slider basé sur la hauteur de la fenêtre et le contenu centré en hauteur
- [x]  Intégration des curseurs flèche pour le slider
- [x]  Lorsque la popup des informations et ouverte puis fermée, le slider ne fonctionne plus
- [x] Ajouter le bouton d’achat en front
- [x] Ajouter en back office un champ texte ou html correspondant au bouton d'achat que je puisse remplir avec le code du bouton. 

![Capture d’écran 2020-12-08 à 15 23 24](https://user-images.githubusercontent.com/75670610/101496001-7f98c600-3969-11eb-984d-8744569ce3c5.png)

Si rien n'est mis dans le champ, ne pas faire apparaître le bouton d'achat sur la page en front

**Comment by 5AMsan** [comment]
On est d'accord, le bouton d'achat c'est le bouton "Support us", n'est-ce pas ?

**Comment by 5AMsan** [comment]
On utiliserait pas le "Checkout link" plutôt que le "Buy button" pour l'intégration ?
Si ça fait pas de différence chez vous, pour moi c'est grave plus simple

**Comment by Pepite-Atelier** [comment]
A quoi ressemble le "Checkout link" ? Je n'ai que le bouton d'achat sur shopify : 
![Capture d’écran 2021-01-05 à 18 17 29](https://user-images.githubusercontent.com/75670610/103677267-5d06c680-4f82-11eb-9ea5-955153944a48.png)

**Comment by 5AMsan** [comment]
Depuis la page du produit :
![image](https://user-images.githubusercontent.com/3309793/103776260-77e34480-502f-11eb-90f9-04310ebb9f67.png)

**Comment by Pepite-Atelier** [comment]
Ah yes ! Par contre on ne peut pas en acheter plusieurs...surtout avec les frais de livraison qui s'ajoutent à chaque achat sur cette méthode.

**Comment by 5AMsan** [comment]
![image](https://user-images.githubusercontent.com/3309793/105215483-9aa64a80-5b51-11eb-831d-c2c21781bd48.png)
Faut modifier le format du bouton sur Shopify du coup

**Comment by 5AMsan** [comment]
Ah. On peut pas...

**Comment by 5AMsan** [comment]
J'ai patché vite fait. On en discute pour voir ce qu'on en fait ?

**Comment by Pepite-Atelier** [comment]
Nous avons testé et ca marche très bien de notre coté c'est super cool !!! J'ai ajouté un autre bouton sur une autre édition et ca comptabilise bien les deux produits (ca marche bien quand on arrive sur une pop-up). Tu voulais qu'on discute de quoi ? On peut s'appeler quand tu veux :) !

**Comment by 5AMsan** [comment]
Bha écoute, si ça fonctionne, c'est bon

**Comment by Pepite-Atelier** [comment]
Je suis sur la stylisation du bouton et du panneau shopify. J'ai ajouté le bouton sur cette page : https://www.pepite.world/editions/acces-internet/ 

J'ai compris qu'il fallait directement toucher aux codes du script que shopify nous donne pour styliser le bouton : j'ai pu donc mettre un border et changer les fonds des boutons. Maintenant, je n'arrive pas à changer la typo des boutons, ni a supprimer l'ombre portée du panneau qui s'ouvre et le margin-top du bouton ajout au panier pour qu'il soit aligné aux autres items. J'ai pourtant ajouter ce code dans la partie personnalisé : 

.shopify-payment-button__button { font-family: 'pipelight';}


.shopify-buy__btn-wrapper {
    padding-top: 1.5rem!important;
text-align: left;
}

:focus {
    outline: none;
}

.shopify-buy__cart {
    -webkit-box-shadow: none;
    box-shadow: none;
    border-left: 1px solid black;
}

.button.shopify:hover {
color: white!important;
	text-rendering:auto;
}

Quand je change la font family directement dans le script, il ne trouve pas la typo pipelight. J'ai cherché dans le wiki du shopify mais je n'ai pas trouvé... https://github.com/Shopify/buy-button-js/blob/master/docs/customization/index.md

Est-ce que tu aurais une idée ? ^^

**Comment by 5AMsan** [comment]
Utilises-tu l'url complète de la typo ?
`https://www.pepite.world/wp-content/themes/pepite-world/dist/fonts/pipe-light-webfont.woff2`
C'est aussi possible que la requête soit bloquée par Shopify (CORS policy), dans ce cas, on y pourra rien.

**Comment by Pepite-Atelier** [comment]
Je vais tester ça ! 👍  Comment tu le rentres en css ? 

.shopify-payment-button__button { font-family: 'https://www.pepite.world/wp-content/themes/pepite-world/dist/fonts/pipe-light-webfont.woff2';} 

Et dans le code script ?

  "button": {
        "font-family": "https://www.pepite.world/wp-content/themes/pepite-world/dist/fonts/pipe-light-webfont.woff2",
        "color": "#000000",
"border": "1px solid black",
        ":hover": {
          "color": "white",
          "background-color": "000000"
        },
        "background-color": "#ffffff",
        ":focus": {
          "background-color": "#000000"
        },
        "border-radius": "25px",
        "padding-left": "24px",
        "padding-right": "24px"
      }
    },
    
    
    
 Tu as une idée pour le margin top du bouton et l'ombre du panneau qui s'ouvre ?

**Comment by 5AMsan** [comment]
Dans le script plutôt, en css ça fonctionnera pas.
Pour l'ombre portée, idem. Si ça peut passer dans le script, en css ça passera pas.

**Comment by Pepite-Atelier** [comment]
D'acc cimer ! La syntaxe est bonne comme je l'ai mise dans le script plus haut ?

**Comment by 5AMsan** [comment]
Pardon j'ai pas fait attention... Non la typo ne passera pas de cette façon... Je regarde si il y a moyen

**Comment by 5AMsan** [comment]
On testerai pas pas l'extension `https://wordpress.org/plugins/wpshopify/` ?

**Comment by Pepite-Atelier** [comment]
Ah ben je ne l'avais pas vu ! Oui on peut tester ! Tu veux que je regarde ?

**Comment by 5AMsan** [comment]
Feu

**Comment by Pepite-Atelier** [comment]
Okay je vais regarder ça et je te dis :) !

**Comment by Pepite-Atelier** [comment]
Alors j'ai bien installé le plugin et je l'ai connecté au shopify ! Apparemment on peut ajouter des shortcodes pour mettre en place les produits / boutons d'achats etc... 

https://docs.wpshop.io/?utm_medium=plugin&utm_source=info&utm_campaign=onboarding#/shortcodes/wps_products_buy_button

Bonne nouvelle, la typo est pris en compte ! Par contre quand j'ai ajouté le shortcode dans le champ que tu as crée, la mise en page est pétée et le bouton ne s'affiche pas :  [wps_products_buy_button title="Asemic #2 / Hollywood Signs" hide_quantity="true"]

Tu as une idée ? On peut s'appeler quand tu veux :) ! 
Petite question aussi, il y aura moyen de remettre comme avant si ca ne marche pas ? Qu'on ne perde pas ce que tu as déja fait pour intégrer le buy button de shopify si le plugin qu'on a trouvé ne marche pas.

**Comment by 5AMsan** [comment]
Oui je sais pourquoi. Il faut que j'interprète le shortcode, ce que je ne faisait pas vu qu'on utilisait du code brut

**Comment by Pepite-Atelier** [comment]
D'acc ! Je vais plus y toucher, tu me diras quand je pourrais re-tester :D ! Ca a l'air d'être une merveille ce plugin si ca marche !

**Comment by 5AMsan** [comment]
Voilà

**Comment by Pepite-Atelier** [comment]
Ah damn ! Je peux facilement revoir les styles pour la partie bouton shopify et carte mais je vais avoir du mal avec le bouton info, le compteur et la flèche de retour. Je vais quand même tester et je te dis !

**Comment by 5AMsan** [comment]
Ils pètent à cause du bouton shopify qui est trop grand, a trop de marge. Une fois retapé, tout rentrera dans l'ordre

**Comment by Pepite-Atelier** [comment]
Stylé ! Merci pour ton aide ! J'ai encore un petit truc, quand on arrive sur cette page https://www.pepite.world/editions/asemic-2/ en passant par édition, le bouton ne s'affiche pas...damned !  Il s'affiche par contre quand on rentre l'url dans la barre d'adresse.

**Comment by 5AMsan** [comment]
Houlà :/ Il va falloir creuser dans l'extension alors

**Comment by Pepite-Atelier** [comment]
Est-ce que ca pourrait venir du fait que quand on est dans une édition et que l'on essaie de revenir sur la page édition via le bouton de retour du navigateur il ne se passe rien ?

**Comment by 5AMsan** [comment]
https://wordpress.org/support/topic/button-not-showing-22/#new-topic-0

**Comment by Pepite-Atelier** [comment]
Okay merci d'avoir fait un topic sur l'extension ! On verra bien !
