### ISSUE TITLE
Home

### ISSUE THREAD

**Issue by 5AMsan** [5AMsan/PepiteWorld#17]
- [x] Après réception des 3 typos/logos, intégration du système d'affichage aléatoire du mot "Pépite" vertical

**Comment by 5AMsan** [comment]
Vous pouvez me dire si la hauteur de ligne est bonne ?

**Comment by Pepite-Atelier** [comment]
Les typos s'affichent bien ! 👍 
Il faudrait grossir la taille et le letter spacing si possible :

letter-spacing: 0.05em;
    font-size: 2em;
    
Merci !

**Comment by 5AMsan** [comment]
OK, jai passé le regles css dans le thème.
Pour ajouter, c'est pas hyper naturel...
Ajouter la typo dans le dossier dist/fonts. Elle doit s'appeler "Pepite-Logo#.otf". Le fichier EOT fait foi. Sans lui pas de prise en compte. On peut s'entendre la-dessus, mais il faut un fichier de référence, même un fichier bidon qui activerai la font.

Ensuite il faut ajouter la config de la font dans les css personnaliser : 
```
@font-face {
    font-family: 'pepite-logo-5';
    src: url('../fonts/Pepite-Logo5.eot');
    src: url('../fonts/Pepite-Logo5.woff2') format('woff2'), url('../fonts/Pepite-Logo5.woff') format('woff'), url('../fonts/Pepite-Logo5.otf') format('truetype');
    font-weight: normal;
    font-style: normal;
}
```

Le reste est gérer côté serveur.

**Comment by Pepite-Atelier** [comment]
Ok c'est nickel ! 👍 👍 👍
