### ISSUE TITLE
Safari bugs

### ISSUE THREAD

**Issue by Pepite-Atelier** [5AMsan/PepiteWorld#19]
- [ ] Sur safari, le logo pepite n'est pas tourné : 

![Capture d’écran 2020-12-14 à 17 10 18](https://user-images.githubusercontent.com/75670610/102105198-668f8980-3e2f-11eb-9bd4-1862c7d9ddb7.png)

**Comment by 5AMsan** [comment]
Je peux avoir des captures du debugger Bastien plz ?

**Comment by 5AMsan** [comment]
MAJ de safari vers v14
