### ISSUE TITLE
Liens non actifs sur l'ensemble des onglets

### ISSUE THREAD

**Issue by Pepite-Atelier** [5AMsan/PepiteWorld#23]
Lorsque nous changeons d'onglet en cliquant sur une zone blanche de l'onglet et non directement sur le nom de la section, l'onglet s'ouvre bien mais l'adresse dans la barre d'adresse ne change pas. Du coup lorsque l'utilisateur ouvre l'onglet comme cela, il se peut que la page ne se charge pas. 

Exemple ici : Après avoir été dans risographie, nous avons cliqué sur la zone de l'onglet Editions (sans cliquer directement sur le nom) et la page Editions s'ouvre mais ne se charge pas : 

<img width="1680" alt="Capture d’écran 2021-01-12 à 17 28 23" src="https://user-images.githubusercontent.com/75670610/104438594-73b7a980-5590-11eb-87dc-a0b328f2daa2.png">

**Comment by Pepite-Atelier** [comment]
Est-ce que c'est possible de faire l'inverse et de garder le click sur les onglets et de faire en sorte que les url changent ?

**Comment by 5AMsan** [comment]
Css - Done
