### ISSUE TITLE
D.A

### ISSUE THREAD

**Issue by Pepite-Atelier** [5AMsan/PepiteWorld#30]
- [x] Micro décalage entre le bouton d’ouverture/fermeture et les projets (qui n'est pas dans un projet).

![Capture d’écran 2021-03-24 à 18 36 17](https://user-images.githubusercontent.com/75670610/112357492-ddaaa880-8ccf-11eb-8f3c-3b36bcca424a.png)

**Comment by 5AMsan** [comment]
A fixer : le menu doit être sous les vignettes au chargement

**Comment by 5AMsan** [comment]
OK pouf FF et Chrome, ça dit quoi sur MacOS ?

**Comment by Pepite-Atelier** [comment]
FF est bon pour moi par contre j'ai toujours le décalage sur Chrome (même en vidant le cache) et sur Safari

**Comment by 5AMsan** [comment]
OK donc c'est un bug lié à MacOS, on va creuser
