### ISSUE TITLE
D.A Projet

### ISSUE THREAD

**Issue by Pepite-Atelier** [5AMsan/PepiteWorld#31]
- [x] **Slider** : Dans la résolution de Renaud 1280x800, le slider est trop petit sur tout les navigateurs (à voir avec lui quelle taille il souhaite) > **RETINA**

- [x] **Video** : Dans ma résolution 1440x900 et celle de Renaud 1280x800, sur **Safari**, il y a une coupure blanche quand les videos bouclent. > **Bast sortir les videos sans le sons**

- [x] La pop-up n'est pas centré sur la page/slider 

- [x] Sur la résolution 1440x900, la taille du carrousel n'est pas de la même taille sur chrome que sur firefox/safari. **Passer 1441 pour le breakpoint**

- [x] Il y a un décalage maintenante de la flèche avec le menu. Il n'y est pas sur Firefox

- [x] Il y a de nouveau ce bug de vidéo qui ne se lancent pas (je pense quand le rémettant après notre crash du responsive tu as du remettre un ancienne version - ca venait du délais de réponse je crois)

**Comment by Pepite-Atelier** [comment]
- [ ] Sur la résolution 1440x900, la taille du carrousel est plus grosse sur firefox/safari que sur chrome. L'idéal serait d'avoir la taille de chrome sur les deux autres navigateur.

- [ ] Les vidéos ne se lancent pas sur chrome mais elles se lancent sur Safari/Firefox (a voir avec Renaud et Vivien car chez eux lorsque on vient de la page D.A la video ne se lance pas mais quand ils rechargent le projet la video se lance). Il y a un ";" après la video ca vient de la peut-être ? 

- [ ] Il y a un flash lorsque la video loop sur Safari sur la la résolution 1440x900 et non sur les résolutions de Renaud et Vivien (safari/firefox).

- [ ] Il y a un décalage maintenante de la flèche avec le menu. Il n'y est pas sur Firefox

- [ ] Parfois, nous arrivons pas à fermer la pop-up

**Comment by 5AMsan** [comment]
@Pepite-Atelier fais de nouveau tickets pour le nouveaux bugs plz.
Assure-toi que ton cache est bien propre, le code pour les vidéos n'a pas changé. Par contre si le bug persiste, il faudra augmenté le délai pour les vidéos. Saches aussi que la charge active de ton ordi est directement liée à la nécessité de modifier ce délai.
