### ISSUE TITLE
Risographie

### ISSUE THREAD

**Issue by Pepite-Atelier** [5AMsan/PepiteWorld#33]
- [ ] **Slider** : il ne se charge pas lorsque l'on ouvre l'onglet à partir d'un autre onglet. Il se charge qu’au chargement de la page Riso.

**Comment by 5AMsan** [comment]
Je dois réécrire ça

**Comment by 5AMsan** [comment]
Pour la taille du slider, c'est lié à la taille des images dans le slider. Il affiche une image sur toute sa hauteur, en respectant le ratio, jusqu'à ce que la largeur soit comblée.

**Comment by Pepite-Atelier** [comment]
- [ ] Il faudrait supprimer les boutons "next/prev" du slider et avoir comme sur le slider D.A les flèches curseur. On voit également une partie du visuel d'avant : 

![Capture d’écran 2021-05-05 à 12 31 09](https://user-images.githubusercontent.com/75670610/117128546-db8f3b80-ad9d-11eb-82bf-fb29ccb9e922.png)

**Comment by 5AMsan** [comment]
On l'a fixé celui-là, non ?

**Comment by Pepite-Atelier** [comment]
Ouaip ! On a plus d'image clone en trop d'après ce que je vois
