### ISSUE TITLE
Responsive Mobile

### ISSUE THREAD

**Issue by Pepite-Atelier** [5AMsan/PepiteWorld#36]
### Global

- [x] Rajouter du padding 5 px à tout le contenu du site

### D.A Item

- [x] Supprimer Glide si pas en desktop
- [x] Rajouter du margin top+bottom sur chaque item

### Fonderie / Fonderie Item

- [x] Réduire dans fontsampler la taille 120px : 80px pour les typo item

###  Pour le mobile landscape : 

- [x] Réduire le contenu de la page d'accueil
- [x] Supprimer l'effet de grossissement du logo 
- [x] Augmenter la taille des typo onglets
- [x] Rajouter de l'espace entre les noms des typos et le bord de l'onglet Riso dans la partie Fonderie
- [x] Sur chrome, le bas de la page des font est coupé.
- [x] Passer "ou prise de rdv au dessus"
- [x] Etendre le responsive du portable landscape jusqu'a 812px (iphoneX landscape)
- [x] J'ai beau changer le "line-height" et le text orientation, je n'arrive pas à modifier le portable landscape en vrai et non sur le simulateur de chrome : 

![IMG_9771](https://user-images.githubusercontent.com/75670610/119464211-ce34f380-bd42-11eb-92b1-1c728d128b53.PNG)
![Capture d’écran 2021-05-25 à 10 18 51](https://user-images.githubusercontent.com/75670610/119464237-d2f9a780-bd42-11eb-9362-5d1586a83fd9.png)

**Comment by 5AMsan** [comment]
> Est-il possible de réduire la taille du nom de chaque typo qu'il rentre dans le contenu de la page ? Idem pour l'intérieur de la font.
Nop, pas sur la page de la typo, c'est à contrôler dans les options FontSampler sinon on ne peux plus tester la taille qui sera donc bloquée.

**Comment by Pepite-Atelier** [comment]
Damn je n'arrive pas à voir certaines modifs que tu as fait sur le mobile, j'ai toujours les sliders D.A / Editions qui ne sont pas centrés. De même la taille de la pop-up à changé, tu pourrais la remettre comme ce que j'avais calé ^^ ? 

Tu n'as pas pu forcer le mobile paysage (résolution moins de 812x375 IponeX) pour qu'il soit comme le paysage de l'iphone X ? J'avais fait également des modifs concernant ce device, j'ai l'impression qu'elles ont été écrasées... tu peux les retrouver dans le css personnalisé. 

Concernant la taille de la typo Fonderie, peut-on réduire la taille si on bloque cette taille uniquement sur ce device ? Ou alors il faut bloquer la taille définitivement desktop/tablette/mobile ? 

Merci :) !

**Comment by 5AMsan** [comment]
Hop,

nan tu ne verra rien, c'est pourquoi je n'ai pas fermé les tickets pour le
moment. Certaines modif sont un peu profondes, je vais mettre en ligne
quand j'aurais réglé les effets de bords dû aux modif.
[image: Photo signature]

Samuel Petat

Responsable Développement et Système & Réseau
[image: Numero de téléphone]

06 49 89 83 61 <0649898361>
[image: Logo Sporting] <https://www.sporting-comm.fr>

272, route de Launaguet - 31200 Toulouse

www.sporting-comm.fr
[image: Logo Facebook]
<https://www.facebook.com/Sporting-Comm-155444555783/> [image: Logo
LinkedIn] <https://www.linkedin.com/company/sporting-comm'/>
<https://www.sporting-promotion.fr/> <https://www.sporting-immobilier.fr/>
<https://www.sporting-groupe.fr/> <https://www.sporting-groupe.fr/>
<https://www.sporting-comm.fr/> <https://www.sporting-village.fr/>


Le lun. 3 mai 2021 à 10:54, Pepite-Atelier ***@***.***> a
écrit :

**Comment by Pepite-Atelier** [comment]
- [ ] Toutes les modifications que j'avais apporté au responsive portable portrait ne sont plus prises en compte, il n'y a d'ailleurs plus le contenu responsive de la page d'acceuil. 

- [ ] Les visuels non animés du slider sont compressés pour entrer dans le slider (on a pu tester sur safari et chrome mais pas sur android) 

- [ ] Sur safari, quand on tappe une fois sur le slider, il tourne deux fois (mobile portrait)

Pour le mobile landscape : 

- [ ] le logo doit être dans son onglet. 

- [ ] Le contenu de la page d'accueil ne s'affiche pas

- [ ] Le contenu est compressé comme dans le mobile portrait.

- [ ] Peut-on rajouter de l'espace entre les noms des typos et le bord de l'onglet Riso dans la partie Fonderie ? 

- [ ] Peut-on réduire la taille des typos dans les pages typos pour qu'elles soient en entier ? 

- [ ] Sur chrome, les images sont coupées en bas dans une font 

- [ ] Les images du slider éditions sont compressés également

**Comment by Pepite-Atelier** [comment]
- [ ] Ajouter des marges aux images + video : BAST

**Comment by 5AMsan** [comment]
Ajouter les paddings sur les contenus
