### ISSUE TITLE
Responsive Tablette portrait

### ISSUE THREAD

**Issue by Pepite-Atelier** [5AMsan/PepiteWorld#37]
### Portrait : 

Toutes les modifs que j'avais fait pour ce viewport ne sont plus prises en compte. Tu pourrais regarder stp @5AMsan ? 
Ligne 1535 du custom css à partir /* RESPONSIVE Tablette Portrait /////////////*/

- [x] Remettre le contenu mobile homepage sur la tablette 

- [x] Désactiver Glide

- [x] Cacher le compteur

- [x] Rajouter du padding à tout le contenu

- [x] Les icones en D.A ne sont pas cliquables

- [x] Ou prise de rdv 

- [x] La hauteur du site est trop grande par rapport a la tablette 

### Horizontal : 

- [x] Le images des sliders sont compréssées (D.A/Riso/Editions) : 

@media screen and (min-width: 813px)
style.min.css:21:42865.glide-wrapper .glide, .glide-wrapper .glide__track, .glide-wrapper ul.glide__slides, .glide-wrapper .glide__slide {
/* height: 100%; */
}

- [ ] Sur chrome, le contenu du site des items fonderie est coupé sur le bas #47

/* IPAD */

@media only screen and (min-device-width : 768px) and (max-device-width : 1024px) and (orientation : landscape){

.pepite-tab-container :not(#post-projet)>.content {
margin-bottom: 4rem;
}}

- [x] Grossir taille pop-up ipad landscape : 

.modal {
width: 80%;
}

**Comment by 5AMsan** [comment]
![image](https://user-images.githubusercontent.com/3309793/115706484-fe692b00-a36d-11eb-879e-70c55c9d39c2.png)

![image](https://user-images.githubusercontent.com/3309793/115706430-edb8b500-a36d-11eb-958d-c4635b2b0ab1.png)

**Comment by Pepite-Atelier** [comment]
- [ ] Les réglages que j'avais fait pour le portrait tablette ne sont plus pris en compte (idem que pour le portable portrait)

- [ ] Les images du sliders sont compressés

- [ ] La hauteur du site est trop grande par rapport a la tablette 

- [ ] Quand on clique sur le blanc dans un onglet, les pages s'ouvrent mais il n'y a pas de contenu 

- [ ] La pop-up des éditions n'est pas centrée sur le slider 

Tablette horizontal :

- [ ] Sur chrome, le contenu du site est coupé sur le bas

**Comment by 5AMsan** [comment]
La partie coupé sur Chrome je vois pas, tu me montres plz ?

**Comment by Pepite-Atelier** [comment]
Tu l'avais déja fixé ce truc de contenu coupé pour le tel donc c'est good !

**Comment by Pepite-Atelier** [comment]
J'ai vu avec l'ipad de Vivien, et pour l'ipad landscape, il faudrait passer mettre les images les unes sous les autres. Le touch du glide bugg pas mal.

**Comment by 5AMsan** [comment]
Y'a pas de swipe, je pense que c'est pour ça que tu dis qu'il bug. Ce sont des boutons comme en desktop

**Comment by Pepite-Atelier** [comment]
Ah yes, mmm du coup c'est un peu compliqué à comprendre du point de vue de l'utilisateur... ce serait possible de passer les images les unes sous les autres pour ce devise aussi ?
