### ISSUE TITLE
Glissement doubles onglets

### ISSUE THREAD

**Issue by Pepite-Atelier** [5AMsan/PepiteWorld#40]
- [x] Lorsque l'on change d'onglet, l'onglet précédent bouge en même temps que celui sur lequel on clique. Est-il possible de fixer l'onglet actif ? 

![onglets-double](https://user-images.githubusercontent.com/75670610/119954342-2d8f3f80-bf9f-11eb-8827-07fdc79c9529.gif)

**Comment by 5AMsan** [comment]
Tu peux virer ce code de ton custom plz :
![image](https://user-images.githubusercontent.com/3309793/120208034-60e6fe00-c22d-11eb-8b99-edf5d2bc024b.png)

**Comment by Pepite-Atelier** [comment]
Ouaip c'est enlevé :) !
