### ISSUE TITLE
Placement des titres onglets Safari

### ISSUE THREAD

**Issue by Pepite-Atelier** [5AMsan/PepiteWorld#41]
- [ ] Sur safari, les titres sont maintenant à droite de l'écran. Ca peut venir du sens d'écriture peut-être ? 

![Capture d’écran 2021-05-28 à 10 29 59](https://user-images.githubusercontent.com/75670610/119955015-e6ee1500-bf9f-11eb-8daa-844882e1270e.png)
![Capture d’écran 2021-05-28 à 10 30 11](https://user-images.githubusercontent.com/75670610/119955031-eb1a3280-bf9f-11eb-8b1b-eb279696f2f2.png)

**Comment by 5AMsan** [comment]
Tu peux virer ce code de ton custom plz :
![image](https://user-images.githubusercontent.com/3309793/120208034-60e6fe00-c22d-11eb-8b99-edf5d2bc024b.png)

**Comment by Pepite-Atelier** [comment]
Tu me l'as déja fait enlever dans le ticket pour les onglets ^^  [(https://github.com/5AMsan/PepiteWorld/issues/40 )]
C'est lié ?

**Comment by 5AMsan** [comment]
oui :D y'a de bonnes chances
