### ISSUE TITLE
Contenu Risographie

### ISSUE THREAD

**Issue by Pepite-Atelier** [5AMsan/PepiteWorld#43]
Lorsque l'on clique sur l'onglet Riso, le contenu texte des encres et papiers ne s'affichent pas : 

![Capture d’écran 2021-05-31 à 15 44 26](https://user-images.githubusercontent.com/75670610/120202778-49a51200-c227-11eb-83ec-7942a8b01e9a.png)

et lorsque l'on recharge le contenu s'affiche : 

![Capture d’écran 2021-05-31 à 15 44 37](https://user-images.githubusercontent.com/75670610/120202935-78bb8380-c227-11eb-80cd-35727a8a3aea.png)

Ca vient peut-être du raccord avec le reste du site ? (le titre de l'onglet n'est pas le même)

**Comment by 5AMsan** [comment]
tes z-index en dur : 
![image](https://user-images.githubusercontent.com/3309793/120205371-2f206800-c22a-11eb-9779-8599efa1a9df.png)

**Comment by Pepite-Atelier** [comment]
Alors j'ai trouvé la spécificité du bug : **Quand on est dans un projet et qu'on va ensuite sur l'onglet riso**, le contenu sur le papier/encre est caché.

**Comment by Pepite-Atelier** [comment]
J'ai trouvé un nouveau bug spécifique à cette page :  **Quand on est dans un projet et qu'on va ensuite sur l'onglet riso**
Les clones du slider apparaissent au mauvais moment.
