### ISSUE TITLE
Menu Ouvert DA

### ISSUE THREAD

**Issue by Pepite-Atelier** [5AMsan/PepiteWorld#48]
Sur la partie DA, ouvrir le menu des projets par default

**Comment by Pepite-Atelier** [comment]
Merci ! Par contre deux petits trucs : 

- Quand on passe dans un projet, le volet projets peut-il se fermer automatiquement ? 
- Quand on recharge la page D.A, le volet est fermé (je pense que ca vient du mauvais nom de la page : Projets Archive)
![Capture d’écran 2021-09-21 à 11 35 54](https://user-images.githubusercontent.com/75670610/134148058-889487a5-d0a6-47f9-9387-74508224f13e.png)

**Comment by 5AMsan** [comment]
C'est bon pour moi, vide bien le cache avant de tester
