### ISSUE TITLE
Balise html <noscript> dans la page d'accueil

### ISSUE THREAD

**Issue by Pepite-Atelier** [5AMsan/PepiteWorld#50]
Nous avons remarqué que les images au hover de studio ne s'affichent plus correctement, en inspectant le code j'ai remarqué des balises <noscript> avant les <img alt>. Ces balises n'étaient pas là avant, en les supprimant tout rentre dans l'ordre. Ces balises sont invisibles dans le code html de la page dans le back office...

![Capture d’écran 2021-09-06 à 12 03 16](https://user-images.githubusercontent.com/75670610/132200182-b3db2c40-eecf-4728-a06d-7f967a360ec4.png)

**Comment by 5AMsan** [comment]
Quels plugins ont été activés récemment ?
[image: Photo signature]

Samuel Petat

Responsable Developpement et Systeme & Reseau
[image: Numero de téléphone]

06 49 89 83 61 <0649898361>
[image: Logo Sporting] <https://www.sporting-comm.fr>

272, route de Launaguet - 31200 Toulouse

T : 05 82 08 26 31

www.sporting-comm.fr
[image: Logo Facebook]
<https://www.facebook.com/Sporting-Comm-155444555783/> [image: Logo
LinkedIn] <https://www.linkedin.com/company/sporting-comm'/>
<https://www.sporting-promotion.fr/> <https://www.sporting-immobilier.fr/>
<https://www.sporting-groupe.fr/> <https://www.sporting-groupe.fr/>
<https://www.sporting-comm.fr/> <https://www.sporting-village.fr/>


Le lun. 6 sept. 2021 à 12:05, Pepite-Atelier ***@***.***> a
écrit :

**Comment by Pepite-Atelier** [comment]
Ah j'avais pas vu ta réponse, j'ai supprimé le plugin de compression d'images que j'avais mis. C'est good je l'ai supprimé !
