### ISSUE TITLE
Bloc Video-Contenu Riso ipad landscape

### ISSUE THREAD

**Issue by Pepite-Atelier** [5AMsan/PepiteWorld#51]
Je n'arrive pas à passer le contenu de la video+texte l'un en dessous de l'autre pour l'ipad landscape, je bloque là... 
J'ai ajouté une ID pour ce bloc : video-contenu. J'ai testé en enlevant et en rajoutant (orientation : landscape) mais rien y fait, je vais me tirer une balle ! 

![Capture d’écran 2021-09-10 à 12 20 41](https://user-images.githubusercontent.com/75670610/132839861-10a5371a-04c3-4003-ad5b-c6e4f27268b3.png)

Ce breakpoint va également me servir pour le retour à la ligne tout pourri en bas de page : 
![Capture d’écran 2021-09-10 à 12 27 33](https://user-images.githubusercontent.com/75670610/132840222-2b3ce05e-61c0-48bb-b694-a0c64f2fded5.png)

J'te jure, en plus ca doit être un truc con mais là je bloque....

**Comment by 5AMsan** [comment]
Utilise cette règle sur ton breakpoint (je te laisse gérer le sélecteur mais celui-ci fonctionne) :
```
.video-contenu > .advgb-columns-container > .advgb-columns-row {
    flex-flow: column;
}
```

**Comment by Pepite-Atelier** [comment]
Cimer je vais regarder ! Mon problème c'est que je n'arrive pas à trouver le breakpoint...

**Comment by 5AMsan** [comment]
@media only screen
and (min-device-width: 813px)
and (max-device-width: 1024px) 
and (orientation: landscape) {
      .video-contenu > .advgb-columns-container > .advgb-columns-row {
      flex-flow: column;
  }
}

**Comment by Pepite-Atelier** [comment]
Bon je vais mettre le feu à mon ordi voila ! Je ne comprends pas...j'ai enrobé le br dans un span class "nobr" dans le html de la page riso pour le supprimer quand on est sur landscape tablette. 

J'ai bien mis : 

@media only screen
and (min-device-width: 813px)
and (max-device-width: 1024px)
and (orientation: landscape) {

.video-contenu > .advgb-columns-container > .advgb-columns-row {
flex-flow: column;
}

#risographie .nobr{
    display: none;
}}

Mais daaaaamn ca ne bouge fucking pas. Si t'as une idée je suis preneur !

**Comment by Pepite-Atelier** [comment]
J'ai tout passé dans ce breakpoint mais rien ne s'applique.... : 


/* Riso */

@media only screen and (min-device-width : 813px) and (max-device-width : 1024px) and (orientation : landscape) {

#risographie p {
    font-size: 15px;
    letter-spacing: .03em;
}

#risographie .wp-block-advgb-columns.advgb-columns-wrapper .advgb-columns-container .advgb-columns.gutter-70>.advgb-column:not(:first-child) {
    margin-left: 40px;
}

.video-contenu > .advgb-columns-container > .advgb-columns-row {
flex-flow: column;
}

.espace-slider-riso {
    height: 0px!important;
}

#risographie .interieur-risographie .nobr {
    display: none;
}

#risographie>*:not(.infobar):not(hr) {
    margin-right: 0px!important;
    margin-left: 0px!important;
}}

**Comment by 5AMsan** [comment]
![image](https://user-images.githubusercontent.com/3309793/135071251-b170fbed-3e2a-478d-ac20-7f17dba76261.png)
Ici ça à l'air ok pourtant, ça dit quoi ?

**Comment by Pepite-Atelier** [comment]
Oui c'est parfait ! C'est bizarre, peut-être un problème de cache ...
