### ISSUE TITLE
Fontsampler issue

### ISSUE THREAD

**Issue by Pepite-Atelier** [5AMsan/PepiteWorld#52]
Nous avons une notif pour le plugin Fontsampler : 

![Capture d’écran 2021-09-10 à 12 31 00](https://user-images.githubusercontent.com/75670610/132840610-315a4203-787b-4f6d-b7e2-72e9f4971242.png)

Tu sais ce que c'est ?

**Comment by 5AMsan** [comment]
Une dépréciation de fonction dans le plugin, il va falloir attendre une mise à jour pour que ce soit fixé
