### ISSUE TITLE
Pastilles projets en dehors du cadre de la page DA

### ISSUE THREAD

**Issue by Pepite-Atelier** [5AMsan/PepiteWorld#53]
La première fois que nous allons sur la page D.A, certaines pastilles sont en dehors de la zone du site. Au rechargement de la page ou lorsque on grab la pastille, elle revient dans la zone du site. Est-il possible que par défaut, les pastilles ne sortent pas du cadre du site ? Merci :) ! 

![Capture d’écran 2021-09-16 à 16 55 58](https://user-images.githubusercontent.com/75670610/133635511-53b080cf-0f5f-4d51-8176-201abe5d90fe.png)

**Comment by 5AMsan** [comment]
Obligé de mettre un délai sur le calcul du draggable.

**Comment by Pepite-Atelier** [comment]
Il est possible de rajouter ce délais quand on charge pour la première fois la page D.A ? Pour le moment, on a le délais que quand on revient sur D.A. Merci :) !

**Comment by 5AMsan** [comment]
Si tu as une apparition -> disparition -> apparition du contenu, ajoute ça dans les CSS personnalisés :
`#post-projet .content { opacity: 0;}`

**Comment by Pepite-Atelier** [comment]
J'ai ajouté #post-projet .content { opacity: 0;} au css personnalisés par contre on a toujours : 
Quand on charge le site et qu'on va sur D.A les pastilles sont en dehors de la page et il n'y a pas le délais d'apparition. 

https://user-images.githubusercontent.com/75670610/135090249-ed94a9ac-637c-4971-ba17-4ce887f2374e.mov

Alors que quand on revient sur D.A à partir d'un projet, les pastilles sont bien dans la zone de la page + délais d'apparition. Tu vois ce que je veux dire ?

**Comment by 5AMsan** [comment]
je te laisse vérifier

**Comment by Pepite-Atelier** [comment]
Parfait !!! Ca tue !!! Merci :D !
