### ISSUE TITLE
Page direction artistique problème apparition opacité 

### ISSUE THREAD

**Issue by Pepite-Atelier** [5AMsan/PepiteWorld#55]
Quand on est dans un projet et qu'on revient sur la page D.A, le contenu de la page met longtemps à apparaitre, j'ai l'impression que c'est un soucis de transition d'opacité.

https://user-images.githubusercontent.com/75670610/134641662-396b4413-fdb1-41e4-b3e0-d1b550baaea9.mov

**Comment by 5AMsan** [comment]
My bad, le timeout pour fixer la position était 10 fois trop important... Faut pas se tromper dans le nombre de zéros
