### ISSUE TITLE
SEO Title projet

### ISSUE THREAD

**Issue by Pepite-Atelier** [5AMsan/PepiteWorld#57]
On est entrain d'optimiser le SEO du site, est-ce que ce serait possible de passer les "p id" des titres projets pop-up en h1 id ? Sinon on se retrouve sans h1 pour les pages projets. 

![Capture d’écran 2021-09-28 à 15 54 30](https://user-images.githubusercontent.com/75670610/135103604-b0d8607d-d4e8-4d06-b235-ad5f64c0b7a3.png)

J'ai la main sur les méta descriptions des pages qui sont éditables comme les projets, les fonts et les éditions mais je ne sais pas comment changer les méta des pages qui ne sont pas éditables : Fonderie, Editions et D.A . Tu saurais par hasard comme je peux m'y prendre ? Merci :) !

**Comment by 5AMsan** [comment]
ok pour la balise H1. Pour les métas je suis pas certains qu'il y ait une différence de méthode selon les pages.

**Comment by Pepite-Atelier** [comment]
Cimer ! Tu me diras quand ce sera en place ! 
Pour les métas je peux les changer avec yoast seo mais j'ai pas accès à toutes les pages. Tu vois ce que je veux dire ?

**Comment by 5AMsan** [comment]
Vérifie si les H1 sortent aux bons endroits. Je regarderai la question des métas.

**Comment by Pepite-Atelier** [comment]
C'est parfait ! Merci beaucoup !

**Comment by Pepite-Atelier** [comment]
C'est good aussi pour les méta j'ai trouvé !
