### ISSUE TITLE
Carroussel Ipad landscape 

### ISSUE THREAD

**Issue by Pepite-Atelier** [5AMsan/PepiteWorld#67]
Ce serait possible de passer les images les unes sous les autres pour ce devise aussi ? On ne comprend pas vraiment qu'il faut cliquer sur le carrousel pour faire bouger les images.

**Comment by 5AMsan** [comment]
J'ai exclu l'iPad de Glide en JS, assure-toi que le cache est bien propre avant de rouvrir le ticket.

**Comment by Pepite-Atelier** [comment]
J'ai bien clean le cache, le guide est bien supprimé mais on ne voit qu'une image : 
![Capture d’écran 2021-10-05 à 12 34 57](https://user-images.githubusercontent.com/75670610/136007560-372ead3a-4329-4290-8dc0-6e968ec68210.png)
