### ISSUE TITLE
Edition - Pépite

### ISSUE THREAD

**Issue by Pepite-Atelier** [5AMsan/PepiteWorld#7]
- [x] Enlever de la marge en haut de la page
- [x] Gérer les marges entres les items (haut/bas)
- [x] Modifier le hover  sans translation juste opacité
- [x] Padding diamond pour avoir le bon écartement entre les boutons

**Comment by 5AMsan** [comment]
Pourquoi il est ouvert ?

**Comment by Pepite-Atelier** [comment]
C'était juste des trucs a faire pour nous c'est done :)

**Comment by Pepite-Atelier** [comment]
- [ ] Ajouter catégorie et prix aux éditions
