### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by Pepite-Atelier** [5AMsan/PepiteWorld#8]
- [x] Renvoi des liens "typographie"; "risographie"; "édite" vers les pages internes du site
- [x] Affichage de la page "mentions légales" au click sur le coeur
- [x] Fermeture de la page "mentions légales" avec le système de croix/curseur (identique à la popup information)
- [x] Renvoi du lien "figure.e" vers le site http://figure-e.com/ 
- [x] Création d'un mailto pour "message@pepite.world"
- [x] ~~Remplacer le "f" et le "i" par la font Signe~~
- [x] Cacher complètement le mot réseau au survol 

![Capture d’écran 2020-12-08 à 14 26 43](https://user-images.githubusercontent.com/75670610/101489583-6e4bbb80-3961-11eb-8e91-8355e5f91fbb.png)

**Comment by 5AMsan** [comment]
Quels sont les glyphes respectifs pour F et I @Pepite-Atelier  ?

**Comment by Pepite-Atelier** [comment]
Ce sont les glyphs "facebook" et "instagram", si c'est plus simple je peux
les assigner à des lettres avec unicode si besoin.




contact@pepite-atelier.com
*pepite-atelier.com <http://pepite-atelier.com/>*

**Comment by 5AMsan** [comment]
Je déplace ce point.

**Comment by Pepite-Atelier** [comment]
Serait-il possible de garder les effets des hover par dessus les onglets ? 
![Capture d’écran 2021-01-05 à 17 04 27](https://user-images.githubusercontent.com/75670610/103669065-29bf3a00-4f78-11eb-80b8-be361397d082.png)
![Capture d’écran 2021-01-05 à 17 04 40](https://user-images.githubusercontent.com/75670610/103669082-2e83ee00-4f78-11eb-8ce8-568bc8a56878.png)

**Comment by Pepite-Atelier** [comment]
- [ ] Enlever le Crop des images studio

**Comment by 5AMsan** [comment]
On est bon, par contre, on ne peut pas sortir le contenu sans que je repasse sur tous les effets.
Je le marque en enhancement.

**Comment by Pepite-Atelier** [comment]
Okay ca roule, ce n'est pas grave si on est bloqué dans le contenu. Par contre as-tu eu le temps de regarder pour l'effet de rebond des noms sur 2015 ? Je te remets ce que je t'avais mis sur fb pour centraliser ici : 

"J'ai trouvé un effet qui ressemble à ce qu'on voulait faire au départ !!! 
C'est ca : https://codepen.io/anishmprasad/pen/XgKoRG

Je l'ai modifié en enlevant le pause sur les hovers, la typo et les couleurs. Je l'ai implanté dans le site ici : /www/wp-content/uploads/js-noms et je l'ai ajouté au hover du mot 2015 (pour conserver l'effet du collectif). 

Alors, est-ce qu'il est possible de contenir la zone du rebond à la zone du contenu de la page d'accueil (pour qu'ils ne passent pas sous les onglets) ? Dans le script il y a une histoire de conteneur window mais je me suis cassé la tête dessus... Est-il également possible d'enclencher le script que quand on est sur le mot 2015 ? Pour le moment je l'ai juste caché quand nous ne somme pas sur 2015 mais j'ai peur que ca fume le processeur ^^ 

Si c'est trop compliqué on garde l'effet que j'ai fait sur collectif 😉 

L'idée est que si tu arrives à le faire sur 2015, je le transfèrerai sur le mot collectif en supprimant l'effet actuel. 

Ah et ca c'est mon pen ^^
https://codepen.io/Hellobast/pen/wvzRErQ
