### ISSUE TITLE
Global 

### ISSUE THREAD

**Issue by Pepite-Atelier** [5AMsan/PepiteWorld#9]
- [x] ~~Après réception des 3 typos/logos, intégration du système d'affichage aléatoire du mot "Pépite" vertical~~
- [x] Intégration de la font “Signe”
- [x] Afin que l'on garde la main sur le loader logo, il faut mieux conserver uniquement le loader crée par Bast avec le plugin PreLoader Plus. 

- [x] Est-il possible de random également le favicon ? J'ai trouvé un lien ici : https://stackoverflow.com/questions/31405460/random-favicon-on-web-page

- [x] Sur la résolution de Vivien en rétina : 2880x1800 les mots de la page d'accueil sont visibles dans les onglets : 
<img width="1680" alt="Capture d’écran 2020-12-08 à 17 20 19" src="https://user-images.githubusercontent.com/75670610/101515371-93025c00-397e-11eb-8291-c2957d6ef9f8.png">
<img width="1680" alt="Capture d’écran 2020-12-08 à 17 20 26" src="https://user-images.githubusercontent.com/75670610/101515377-94338900-397e-11eb-8b7f-3423e96ff83b.png">

**Comment by 5AMsan** [comment]
Les favicons seront à déposer dans le thème dans le répertoire `dist/favicons/`, en *.png* uniquement.

**Comment by Pepite-Atelier** [comment]
J'ai remplacé la font Signe sur notre drive partagé.
-
Bast

**Comment by Pepite-Atelier** [comment]
Où se trouve le répertoire dist/favicons/ ? Nous ne le trouvons pas dans <code> ^^
Merci ! 

Bast

**Comment by Pepite-Atelier** [comment]
Peux-tu mettre un accent à Éditions stp sur l'onglet ? Je n'ai pas trouvé dans le menu... merci :) !
